<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>buckettie</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Buckettie.Server/Buckettie.Server.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Buckettie.Cli.Tests" />
  </ItemGroup>
</Project>
